# Generated by Django 4.2.1 on 2023-06-15 14:14

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('breed', models.CharField(max_length=25)),
                ('spcies', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('price', models.FloatField(default=1000)),
                ('height', models.FloatField()),
                ('image', models.ImageField(default=' ', upload_to='media')),
            ],
            options={
                'db_table': 'pets',
            },
            managers=[
                ('pet', django.db.models.manager.Manager()),
            ],
        ),
    ]
