# Generated by Django 3.2.8 on 2023-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='pets',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AddField(
            model_name='tag',
            name='pet',
            field=models.ManyToManyField(to='pets.Pet'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tagname',
            field=models.CharField(default=' ', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
