# Generated by Django 4.2.1 on 2023-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('delivered', 'deliverd'), ('cancelled', 'cancelled')], default='new', max_length=20),
        ),
    ]
